### ISSUE TITLE
Vehicles consume fuel very fast

### ISSUE THREAD

**Issue by DubTheGrub** [FlansMods/FlansMod#1270]
Minecraft 1.12.2
Flans Mod Beta8 5.6.0
(Tested with WW2 and Modern Warfare pack.)

It seems that vehicles like tanks, cars and ships guzzle down fuel extremely fast regardless of engine type, speed or other variables. I'm pretty sure this issue has popped up while fixing the infinite fuel bug of Beta7.
Thanks

Edit: I did forget to mention that ships do as well have this issue. Planes and helicopters are unaffected however.

-Dub

**Comment by JValor2417** [comment]
I tried completely remaking the MW Content Pack Humvee from scratch in combination with Flans mod 5.6 Beta V8 including a slew of different fields/stats, and I can second that this is more than likely a bug with the mod and not a config in the category. (felt I'd back your issue up @DubTheGrub  as some of the issues on this git repo have been due to config or asset reference errors, and this is for sure not one of those..)

**Comment by DubTheGrub** [comment]
> I tried completely remaking the MW Content Pack Humvee from scratch in combination with Flans mod 5.6 Beta V8 including a slew of different fields/stats, and I can second that this is more than likely a bug with the mod and not a config in the category. (felt I'd back your issue up @DubTheGrub as some of the issues on this git repo have been due to config or asset reference errors, and this is for sure not one of those..)

Alright. Thank you for letting me know!

**Comment by Bekos-von-Nimmerland** [comment]
Fixed this issue a long time ago, but registered only today. It's really hard to transmit all improvements from one release(beta.8 to beta.9, then to beta.10) into another as it releases. So I will contribute if possible, firstly ask some permission as it is major vehicle files' change( add some strings of code to every file in content packs). But as in real life you will need to wait until fill machine's fuel tank with Jerry cans.

**Comment by JACHUPOL** [comment]
wow there was an update and this still isn't fixed, since this is one of the biggest problems

**Comment by Ennsomniac2** [comment]
Yeah, this issue still exists.
